In [1]:
import cv2
import numpy as np

In [35]:
img = cv2.imread('cyz01.png', cv2.IMREAD_GRAYSCALE)


In [36]:
print(img.shape) # (h,w,c)
print(img.size) # 像素总数目
print(img.dtype)
print(img)


(61, 61)
3721
uint8
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [12]:
print(min(img[28]))

0


In [23]:
sum(img[2][1:4])

765

In [33]:
for i in range(60):
    for j in range(60):
        if ((sum(img[i*3][j*3:j*3+3])+sum(img[i*3+1][j*3:j*3+3])+sum(img[i*3+2][j*3:j*3+3])/9)) <245:
            s[i][j]=0
        else:
            s[i][j]=255

In [40]:
cv2.imwrite('cyzf.png',s)

True

In [25]:
s = np.random.rand(60, 60)

In [19]:
s

array([[0.34690256, 0.00148494, 0.66916764],
       [0.37638285, 0.88639188, 0.53258219],
       [0.38074418, 0.8305447 , 0.32705382]])

In [47]:
for i in range(60):
    for j in range(60):
        if (img[i][j]<100):
            s[i][j]=0
        else:
            s[i][j]=255
cv2.imwrite('cyzf.png',s)

True

In [48]:
for i in range(60):
    for j in range(60):
        if (s[i][j]<100):
            print(f'({i}, {j})')


(1, 9)
(1, 10)
(1, 11)
(2, 9)
(2, 10)
(2, 11)
(2, 12)
(2, 13)
(3, 11)
(3, 12)
(3, 13)
(3, 14)
(4, 12)
(4, 13)
(4, 14)
(4, 15)
(4, 16)
(5, 14)
(5, 15)
(5, 16)
(5, 17)
(6, 15)
(6, 16)
(6, 17)
(6, 18)
(7, 16)
(7, 17)
(7, 18)
(7, 19)
(8, 17)
(8, 18)
(8, 19)
(8, 20)
(9, 18)
(9, 19)
(9, 20)
(9, 21)
(10, 6)
(10, 7)
(10, 8)
(10, 9)
(10, 10)
(10, 11)
(10, 19)
(10, 20)
(10, 21)
(10, 22)
(11, 6)
(11, 7)
(11, 8)
(11, 9)
(11, 10)
(11, 11)
(11, 12)
(11, 13)
(11, 14)
(11, 15)
(11, 20)
(11, 21)
(11, 22)
(11, 23)
(12, 7)
(12, 8)
(12, 9)
(12, 10)
(12, 11)
(12, 12)
(12, 13)
(12, 14)
(12, 15)
(12, 16)
(12, 17)
(12, 21)
(12, 22)
(12, 23)
(12, 24)
(13, 7)
(13, 11)
(13, 12)
(13, 13)
(13, 14)
(13, 15)
(13, 16)
(13, 17)
(13, 18)
(13, 22)
(13, 23)
(13, 24)
(13, 25)
(14, 11)
(14, 14)
(14, 15)
(14, 16)
(14, 17)
(14, 18)
(14, 19)
(14, 23)
(14, 24)
(14, 25)
(14, 26)
(15, 8)
(15, 10)
(15, 17)
(15, 18)
(15, 19)
(15, 20)
(15, 24)
(15, 25)
(15, 26)
(15, 27)
(16, 8)
(16, 9)
(16, 10)
(16, 13)
(16, 14)
(16, 19)
(16, 20)
(

In [ ]:
#tye!